name: Publish Backend to Virtual Machine

on:
  push:
    # Only run this workflow if it is a commit to main.
    branches:
      - main
    # Only run this workflow if the commit has modified files from backend
    paths:
      - backend/**
      - .github/workflows/build-backend.yml

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag backend-bytepeeps

      - name: Export image to tar
        run: docker save -o backend-bytepeeps.tar backend-bytepeeps

      - name: scp command to copy image to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: 'backend/backend-bytepeeps.tar' # doesn't follow the default workdir
          target: '~/images'
          strip_components: 1

      - name: ssh commands to load and deploy the docker containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker load < ~/images/backend-bytepeeps.tar && docker compose up -d && yes | docker image prune -a

      # Command
      # act -s KEY="$(< ssh-key.txt)" --rebuild --secret-file my.secrets -W .github/workflows/local-build-backend.yml
